# Generated by Django 5.0.10 on 2025-10-31 07:47

from django.db import migrations


def create_default_sections(apps, schema_editor):
    """Create default section for all existing surveys and link questions to it."""
    Survey = apps.get_model('djf_surveys', 'Survey')
    Section = apps.get_model('djf_surveys', 'Section')
    Question = apps.get_model('djf_surveys', 'Question')
    
    for survey in Survey.objects.all():
        # Create default section for each survey
        default_section, created = Section.objects.get_or_create(
            survey=survey,
            ordering=0,
            defaults={
                'name': 'Main',
                'description': 'Default section'
            }
        )
        
        # Link all questions without a section to the default section
        Question.objects.filter(survey=survey, section__isnull=True).update(
            section=default_section
        )


def reverse_default_sections(apps, schema_editor):
    """Remove default sections if rolling back."""
    Section = apps.get_model('djf_surveys', 'Section')
    # Remove all sections named 'Main' with ordering 0
    Section.objects.filter(name='Main', ordering=0).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0023_answer_file_value_alter_question_type_field_section_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_sections, reverse_default_sections),
    ]
