# Generated by Django 5.2.7 on 2025-11-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0024_create_default_sections'),
    ]

    operations = [
        # Add file_url field to Answer model
        migrations.AddField(
            model_name='answer',
            name='file_url',
            field=models.URLField(
                blank=True,
                help_text='Accessible URL for uploaded file',
                max_length=500,
                null=True,
                verbose_name='file URL'
            ),
        ),
        # Add branching fields to Question model
        migrations.AddField(
            model_name='question',
            name='enable_branching',
            field=models.BooleanField(
                default=False,
                help_text='Enable section branching for this question (radio type only)',
                verbose_name='enable branching'
            ),
        ),
        migrations.AddField(
            model_name='question',
            name='branch_config',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Maps each choice to target section ID',
                verbose_name='branch configuration'
            ),
        ),
        # Create StorageConfiguration model
        migrations.CreateModel(
            name='StorageConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(
                    choices=[('local', 'Local Storage'), ('google_drive', 'Google Drive')],
                    default='local',
                    max_length=20,
                    verbose_name='storage provider'
                )),
                ('credentials', models.JSONField(
                    blank=True,
                    default=dict,
                    help_text='Encrypted credentials for cloud storage',
                    verbose_name='credentials'
                )),
                ('config', models.JSONField(
                    blank=True,
                    default=dict,
                    help_text='Additional configuration options',
                    verbose_name='configuration'
                )),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'storage configuration',
                'verbose_name_plural': 'Storage Configurations',
                'ordering': ['-created_at'],
            },
        ),
    ]
