# Generated by Django 5.0.10 on 2025-11-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0025_add_storage_and_branching_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at'], 'verbose_name': 'answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='answer2',
            options={'ordering': ['-created_at'], 'verbose_name': 'answer for Question2', 'verbose_name_plural': 'Rating Answers'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['name'], 'verbose_name': 'direction', 'verbose_name_plural': 'Directions'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['ordering'], 'verbose_name': 'question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='question2',
            options={'ordering': ['ordering'], 'verbose_name': 'rating question', 'verbose_name_plural': 'Rating Questions'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['survey', 'ordering'], 'verbose_name': 'section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['created_at'], 'verbose_name': 'survey', 'verbose_name_plural': 'Surveys'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['-updated_at'], 'verbose_name': 'user answer', 'verbose_name_plural': 'User Answers'},
        ),
        migrations.AlterModelOptions(
            name='useranswer2',
            options={'ordering': ['-updated_at'], 'verbose_name': 'user answer for Question2', 'verbose_name_plural': 'User Rating Answers'},
        ),
        migrations.AlterModelOptions(
            name='userrating',
            options={'ordering': ['-created_at'], 'verbose_name': 'user rating', 'verbose_name_plural': 'Teacher Ratings'},
        ),
        migrations.AddField(
            model_name='question',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of characters allowed (for text fields). Leave blank for default maximum.', null=True, verbose_name='maximum length'),
        ),
        migrations.AddField(
            model_name='question',
            name='min_length',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum number of characters required (for text fields). Leave blank for no minimum.', null=True, verbose_name='minimum length'),
        ),
        migrations.AddField(
            model_name='question',
            name='regex_pattern',
            field=models.CharField(blank=True, help_text='Regular expression pattern for validation (e.g., ^[A-Z0-9]+$ for alphanumeric). Leave blank for no pattern matching.', max_length=500, null=True, verbose_name='regex pattern'),
        ),
        migrations.AddField(
            model_name='question',
            name='validation_message',
            field=models.CharField(blank=True, help_text='Custom error message to display when validation fails. Leave blank for default message.', max_length=200, null=True, verbose_name='validation message'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.TextField(help_text='Value of the answer provided by the user.', verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='answer2',
            name='value',
            field=models.PositiveIntegerField(help_text='Rating value, for example, from 1 to 5.', verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text='If field type is radio, select, or multi-select, enter options separated bycommas. Example: Male, Female', null=True, verbose_name='choices'),
        ),
        migrations.AlterField(
            model_name='question',
            name='help_text',
            field=models.CharField(blank=True, help_text='You can enter help text here.', max_length=200, null=True, verbose_name='help text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='key',
            field=models.CharField(blank=True, help_text='Unique key automatically generated from question text. Leave blank to auto-generate.', max_length=225, null=True, unique=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(help_text='Enter your question here.', max_length=500, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Determines the order of questions within the survey.', verbose_name='ordering'),
        ),
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True, help_text='If checked, users must answer this question.', verbose_name='required'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_field',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Text'), (1, 'Number'), (2, 'Radio'), (3, 'Select'), (4, 'Multi Select'), (5, 'Text Area'), (6, 'URL'), (7, 'Email'), (8, 'Date'), (9, 'Rating'), (10, 'File Upload')], verbose_name='field type'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='choices',
            field=models.TextField(blank=True, help_text='Number of stars in the rating, for example: 5', null=True, verbose_name='choices'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='help_text',
            field=models.CharField(blank=True, help_text='You can enter help text here.', max_length=200, null=True, verbose_name='help text'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='key',
            field=models.CharField(blank=True, help_text='Unique key automatically generated from question text. Leave blank to auto-generate.', max_length=225, null=True, unique=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='label',
            field=models.CharField(help_text='Enter your question here.', max_length=500, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Determines the order of questions within the survey.', verbose_name='ordering'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='required',
            field=models.BooleanField(default=True, help_text='If checked, users must answer this question.', verbose_name='required'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='ordering'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='can_anonymous_user',
            field=models.BooleanField(default=False, help_text='If checked, unauthenticated users can submit responses.', verbose_name='allow anonymous submissions'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='deletable',
            field=models.BooleanField(default=True, help_text='If unchecked, users cannot delete their submissions.', verbose_name='deletable'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='duplicate_entry',
            field=models.BooleanField(default=False, help_text='If checked, users can submit multiple responses.', verbose_name='allow multiple submissions'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='editable',
            field=models.BooleanField(default=True, help_text='If unchecked, users cannot edit their submissions.', verbose_name='editable'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='notification_to',
            field=models.TextField(blank=True, help_text='Enter email addresses to notify on submission', null=True, verbose_name='notification email'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='private_response',
            field=models.BooleanField(default=False, help_text='If checked, only administrators and owners can access responses.', verbose_name='private response'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='success_page_content',
            field=models.TextField(blank=True, help_text='You can customize the success page here. HTML syntax is supported.', null=True, verbose_name='success page content'),
        ),
    ]
