# Generated by Django 5.0.10 on 2025-11-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0026_alter_answer_options_alter_answer2_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='file_organization',
            field=models.CharField(choices=[('response', 'By Response (One folder per submission)'), ('question', 'By Question (One folder per question)')], default='response', help_text='Choose how to organize uploaded files: by response or by question', max_length=20, verbose_name='file organization'),
        ),
    ]
