# Generated by Django 5.0.10 on 2025-11-02 02:56

import django.db.models.deletion
import djf_surveys.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0027_survey_file_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration can be active at a time', verbose_name='Active Configuration')),
                ('site_name', models.CharField(default='Survey System', help_text='Website title displayed in header and browser tab', max_length=200, verbose_name='Site Name')),
                ('site_tagline', models.CharField(blank=True, help_text='Short description shown under site name', max_length=500, verbose_name='Site Tagline')),
                ('logo', models.ImageField(blank=True, help_text='Site logo (recommended: 200x60px, PNG with transparency)', null=True, upload_to=djf_surveys.models.upload_site_logo, verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, help_text='Browser favicon (recommended: 32x32px, PNG or ICO)', null=True, upload_to=djf_surveys.models.upload_site_favicon, verbose_name='Favicon')),
                ('primary_color', models.CharField(default='#6366f1', help_text='Main brand color (hex code, e.g., #6366f1)', max_length=7, verbose_name='Primary Color')),
                ('secondary_color', models.CharField(default='#8b5cf6', help_text='Secondary accent color (hex code)', max_length=7, verbose_name='Secondary Color')),
                ('accent_color', models.CharField(default='#ec4899', help_text='Accent/highlight color (hex code)', max_length=7, verbose_name='Accent Color')),
                ('homepage_title', models.CharField(default='Welcome to Our Survey Platform', help_text='Main heading on homepage hero section', max_length=200, verbose_name='Homepage Title')),
                ('homepage_subtitle', models.TextField(blank=True, help_text='Description text under homepage title', verbose_name='Homepage Subtitle')),
                ('homepage_banner', models.ImageField(blank=True, help_text='Hero section background image (recommended: 1920x600px)', null=True, upload_to=djf_surveys.models.upload_homepage_banner, verbose_name='Homepage Banner')),
                ('homepage_video_url', models.URLField(blank=True, help_text='YouTube or Vimeo video URL for homepage', verbose_name='Homepage Video URL')),
                ('footer_text', models.TextField(blank=True, help_text='Copyright and contact information', verbose_name='Footer Text')),
                ('footer_address', models.TextField(blank=True, help_text='Organization address', verbose_name='Address')),
                ('footer_phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('footer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('about_page_content', models.TextField(blank=True, help_text='Content for /about page (supports HTML)', verbose_name='About Page Content')),
                ('contact_page_content', models.TextField(blank=True, help_text='Content for /contact page (supports HTML)', verbose_name='Contact Page Content')),
                ('terms_page_content', models.TextField(blank=True, help_text='Terms of service content (supports HTML)', verbose_name='Terms & Conditions')),
                ('privacy_page_content', models.TextField(blank=True, help_text='Privacy policy content (supports HTML)', verbose_name='Privacy Policy')),
                ('enable_user_registration', models.BooleanField(default=True, help_text='Allow new users to register', verbose_name='Enable User Registration')),
                ('enable_anonymous_surveys', models.BooleanField(default=True, help_text='Allow surveys to accept anonymous responses', verbose_name='Enable Anonymous Surveys')),
                ('show_survey_stats', models.BooleanField(default=True, help_text='Display survey participation stats on homepage', verbose_name='Show Survey Statistics')),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description (160 characters recommended)', verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords, comma-separated', max_length=500, verbose_name='Meta Keywords')),
                ('google_analytics_id', models.CharField(blank=True, help_text='GA tracking ID (e.g., G-XXXXXXXXXX)', max_length=50, verbose_name='Google Analytics ID')),
                ('version', models.PositiveIntegerField(default=1, help_text='Configuration version number', verbose_name='Version')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this configuration', verbose_name='Admin Notes')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfigChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('activated', 'Activated'), ('deactivated', 'Deactivated')], max_length=20, verbose_name='Action')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON object containing field changes', verbose_name='Changes')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='djf_surveys.siteconfig', verbose_name='Configuration')),
            ],
            options={
                'verbose_name': 'Site Config Change Log',
                'verbose_name_plural': 'Site Config Change Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
