# Generated by Django 5.2.7 on 2025-11-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djf_surveys', '0028_siteconfig_siteconfigchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='browser',
            field=models.CharField(blank=True, help_text='Browser name and version', max_length=100, null=True, verbose_name='browser'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='device',
            field=models.CharField(blank=True, help_text='Device type (Desktop, Mobile, Tablet)', max_length=100, null=True, verbose_name='device'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the device', null=True, verbose_name='IP address'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='os',
            field=models.CharField(blank=True, help_text='Operating system', max_length=100, null=True, verbose_name='operating system'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser user agent string', null=True, verbose_name='user agent'),
        ),
    ]
